--- #YAML:1.0
name:               Geo-Coordinates-UTM
version:            0.11
abstract:           Convert LatLon to UTM and vice versa
author:
    - Graham Crookham (grahamc@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
